return {
  "williamboman/mason.nvim",
  cmd = "Mason",
  keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
  build = ":MasonUpdate",
  opts = {
    ui = {
      icons = {
        package_installed = "✓",
        package_pending = "➜",
        package_uninstalled = "✗",
      },
    },
    ensure_installed = {
      "stylua",
      "shfmt",
      "yamlfix",
      "yamlfmt",
      "yaml-language-server",
      "vim-language-server",
      "textlint",
      "vim-language-server",
      "google-java-format",
      "sqlls",
      "standardjs",
      "sqlfmt",
      "sql-formatter",
      "sonarlint-language-server",
      "python-lsp-server",
      "prettierd",
      "kotlin-language-server",
      "htmx-lsp",
      "js-debug-adapter",
      "jsonlint",
      "java-test",
      "java-debug-adapter",
      "htmlbeautifier",
      "html-lsp",
      "gradle-language-server",
      "gotestsum",
      "gotests",
      "go-debug-adapter",
      "golines",
      "golangci-lint-langserver",
      "golangci-lint",
      "goimports-reviser",
      "css-variables-language-server",
      "cssmodules-language-server",
      "css-lsp",
      "ansible-language-server",
      "angular-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "gitui",
      "gofumpt",
      "goimports",
      "gopls",
      "hadolint",
      "jdtls",
      "xmlformatter",
      "json-lsp",
      "lua-language-server",
      "markdownlint",
      "marksman",
      "prettier",
      "pyright",
      "ruff-lsp",
      "some-sass-language-server",
      "stylelint",
      "tailwindcss-language-server",
      "typescript-language-server",
      "phpcs",
      "php-cs-fixer",
      "actionlint",
      "ansible-lint",
      "antlers-language-server",
      "black",
      "bash-language-server",
      "blade-formatter",
      "dot-language-server",
      "eslint_d",
      "flake8",
      "intelephense",
      "nginx-language-server",
      "php-debug-adapter",
      "phpstan",
      "pint",
      "rustywind",
      "shellcheck",
    },
  },
}
