return {
  "mason-org/mason.nvim",
  cmd = "Mason",
  keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
  build = ":MasonUpdate",
  opts = {
    ui = {
      icons = {
        package_installed = "✓",
        package_pending = "➜",
        package_uninstalled = "✗",
      },
    },
    ensure_installed = {
      "actionlint",
      "angular-language-server",
      "ansible-language-server",
      "ansible-lint",
      "antlers-language-server",
      "bash-language-server",
      "black",
      "blade-formatter",
      "css-lsp",
      "css-variables-language-server",
      "cssmodules-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "dot-language-server",
      "eslint_d",
      "flake8",
      "gitui",
      "go-debug-adapter",
      "goimports",
      "goimports-reviser",
      "golangci-lint",
      "golangci-lint-langserver",
      "gofumpt",
      "golines",
      "gopls",
      "gotests",
      "gotestsum",
      "gradle-language-server",
      "google-java-format",
      "hadolint",
      "html-lsp",
      "htmlbeautifier",
      "htmx-lsp",
      "intelephense",
      "java-debug-adapter",
      "java-test",
      "jdtls",
      "js-debug-adapter",
      "json-lsp",
      "jsonlint",
      "kotlin-language-server",
      "lua-language-server",
      "markdownlint",
      "marksman",
      "nginx-language-server",
      "php-cs-fixer",
      "php-debug-adapter",
      "phpcs",
      "phpstan",
      "prettier",
      "prettierd",
      "pyright",
      "python-lsp-server",
      "ruff-lsp",
      "shfmt",
      "shellcheck",
      "some-sass-language-server",
      "sonarlint-language-server",
      "sql-formatter",
      "sqlfmt",
      "sqlls",
      "standardjs",
      "stylua",
      "tailwindcss-language-server",
      "templ",
      "textlint",
      "typescript-language-server",
      "vim-language-server",
      "xmlformatter",
      "yaml-language-server",
      "yamlfix",
      "yamlfmt",
    },
  },

  {
    "mason-org/mason-lspconfig.nvim",
  },
  {
    "neovim/nvim-lspconfig",
  },
}

-- return {
--   {
--     "mason-org/mason.nvim",
--     version = "^1.0.0",
--     cmd = "Mason",
--     keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
--     build = ":MasonUpdate",
--     opts = {
--       ui = {
--         icons = {
--           package_installed = "✓",
--           package_pending = "➜",
--           package_uninstalled = "✗",
--         },
--       },
--       ensure_installed = {
--         "stylua",
--         "shfmt",
--         "yamlfix",
--         "yamlfmt",
--         "yaml-language-server",
--         "vim-language-server",
--         "textlint",
--         "vim-language-server",
--         "google-java-format",
--         "sqlls",
--         "standardjs",
--         "sqlfmt",
--         "sql-formatter",
--         "sonarlint-language-server",
--         "python-lsp-server",
--         "prettierd",
--         "kotlin-language-server",
--         "htmx-lsp",
--         "js-debug-adapter",
--         "jsonlint",
--         "java-test",
--         "java-debug-adapter",
--         "htmlbeautifier",
--         "html-lsp",
--         "gradle-language-server",
--         "gotestsum",
--         "gotests",
--         "go-debug-adapter",
--         "golines",
--         "golangci-lint-langserver",
--         "golangci-lint",
--         "goimports-reviser",
--         "css-variables-language-server",
--         "cssmodules-language-server",
--         "css-lsp",
--         "ansible-language-server",
--         "angular-language-server",
--         "docker-compose-language-service",
--         "dockerfile-language-server",
--         "gitui",
--         "gofumpt",
--         "goimports",
--         "gopls",
--         "hadolint",
--         "jdtls",
--         "xmlformatter",
--         "json-lsp",
--         "lua-language-server",
--         "markdownlint",
--         "marksman",
--         "prettier",
--         "pyright",
--         "ruff-lsp",
--         "some-sass-language-server",
--         "stylelint",
--         "tailwindcss-language-server",
--         "typescript-language-server",
--         "phpcs",
--         "php-cs-fixer",
--         "actionlint",
--         "ansible-lint",
--         "antlers-language-server",
--         "black",
--         "bash-language-server",
--         "blade-formatter",
--         "dot-language-server",
--         "eslint_d",
--         "flake8",
--         "intelephense",
--         "nginx-language-server",
--         "php-debug-adapter",
--         "phpstan",
--         "shellcheck",
--         "templ",
--       },
--     },
--   },
--   { "mason-org/mason-lspconfig.nvim", version = "^1.0.0" },
-- }
