return {
  "nvim-treesitter/nvim-treesitter",
  version = false, -- last release is way too old and doesn't work on Windows
  build = ":TSUpdate",
  event = { "LazyFile", "VeryLazy" },
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "bash",
      "angular",
      "c",
      "css",
      "csv",
      "dockerfile",
      "gitignore",
      "go",
      "gomod",
      "gowork",
      "gosum",
      "gotmpl",
      "html",
      "http",
      "java",
      "kotlin",
      "latex",
      "markdown",
      "markdown_inline",
      "proto",
      "scss",
      "sql",
      "ssh_config",
      "templ",
      "terraform",
      "tmux",
      "diff",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "php",
      "phpdoc",
    },
    -- query_linter = {
    --   enable = true,
    --   use_virtual_text = true,
    --   lint_events = { "BufWrite", "CursorHold" },
    -- },
  },
}
